### ISSUE TITLE
extract_splice_sites.py

### ISSUE THREAD

**Issue by tiramisutes** [infphilo/hisat#5]
I found some problem when run hisat‘s extract_splice_sites.py,

Traceback (most recent call last):
  File "extract_splice_sites.py", line 244, in <module>
    extract_splice_sites(sys.argv[1])
  File "extract_splice_sites.py", line 190, in extract_splice_sites
    trans_dic, trans_ids = extract_transcripts(gtf_fname, verbose = False)
  File "extract_splice_sites.py", line 143, in extract_transcripts
    transcript_avg_length = float(transcript_length_sum) / transcript_counts
ZeroDivisionError: float division

**Comment by infphilo** [comment]
This problem shouldn't happen if you use a standard GTF format.  BTW, we updated that script recently if you want to give it a try.

Thanks,
Daehwan

**Comment by tiramisutes** [comment]
Ok,I will try again,thanks
